// Code generated by entc, DO NOT EDIT.

package tinyurl

const (
	// Label holds the string label denoting the tinyurl type in the database.
	Label = "tiny_url"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// Table holds the table name of the tinyurl in the database.
	Table = "tiny_urls"
)

// Columns holds all SQL columns for tinyurl fields.
var Columns = []string{
	FieldID,
	FieldURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint64) error
)
