// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"shor_url/ent/migrate"

	"shor_url/ent/tinyurl"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// TinyURL is the client for interacting with the TinyURL builders.
	TinyURL *TinyURLClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.TinyURL = NewTinyURLClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		TinyURL: NewTinyURLClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		TinyURL: NewTinyURLClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		TinyURL.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.TinyURL.Use(hooks...)
}

// TinyURLClient is a client for the TinyURL schema.
type TinyURLClient struct {
	config
}

// NewTinyURLClient returns a client for the TinyURL from the given config.
func NewTinyURLClient(c config) *TinyURLClient {
	return &TinyURLClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tinyurl.Hooks(f(g(h())))`.
func (c *TinyURLClient) Use(hooks ...Hook) {
	c.hooks.TinyURL = append(c.hooks.TinyURL, hooks...)
}

// Create returns a create builder for TinyURL.
func (c *TinyURLClient) Create() *TinyURLCreate {
	mutation := newTinyURLMutation(c.config, OpCreate)
	return &TinyURLCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TinyURL entities.
func (c *TinyURLClient) CreateBulk(builders ...*TinyURLCreate) *TinyURLCreateBulk {
	return &TinyURLCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TinyURL.
func (c *TinyURLClient) Update() *TinyURLUpdate {
	mutation := newTinyURLMutation(c.config, OpUpdate)
	return &TinyURLUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TinyURLClient) UpdateOne(tu *TinyURL) *TinyURLUpdateOne {
	mutation := newTinyURLMutation(c.config, OpUpdateOne, withTinyURL(tu))
	return &TinyURLUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TinyURLClient) UpdateOneID(id uint64) *TinyURLUpdateOne {
	mutation := newTinyURLMutation(c.config, OpUpdateOne, withTinyURLID(id))
	return &TinyURLUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TinyURL.
func (c *TinyURLClient) Delete() *TinyURLDelete {
	mutation := newTinyURLMutation(c.config, OpDelete)
	return &TinyURLDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *TinyURLClient) DeleteOne(tu *TinyURL) *TinyURLDeleteOne {
	return c.DeleteOneID(tu.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *TinyURLClient) DeleteOneID(id uint64) *TinyURLDeleteOne {
	builder := c.Delete().Where(tinyurl.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TinyURLDeleteOne{builder}
}

// Query returns a query builder for TinyURL.
func (c *TinyURLClient) Query() *TinyURLQuery {
	return &TinyURLQuery{
		config: c.config,
	}
}

// Get returns a TinyURL entity by its id.
func (c *TinyURLClient) Get(ctx context.Context, id uint64) (*TinyURL, error) {
	return c.Query().Where(tinyurl.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TinyURLClient) GetX(ctx context.Context, id uint64) *TinyURL {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TinyURLClient) Hooks() []Hook {
	return c.hooks.TinyURL
}
