// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shor_url/ent/predicate"
	"shor_url/ent/tinyurl"
	"sync"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeTinyURL = "TinyURL"
)

// TinyURLMutation represents an operation that mutates the TinyURL nodes in the graph.
type TinyURLMutation struct {
	config
	op            Op
	typ           string
	id            *uint64
	url           *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*TinyURL, error)
	predicates    []predicate.TinyURL
}

var _ ent.Mutation = (*TinyURLMutation)(nil)

// tinyurlOption allows management of the mutation configuration using functional options.
type tinyurlOption func(*TinyURLMutation)

// newTinyURLMutation creates new mutation for the TinyURL entity.
func newTinyURLMutation(c config, op Op, opts ...tinyurlOption) *TinyURLMutation {
	m := &TinyURLMutation{
		config:        c,
		op:            op,
		typ:           TypeTinyURL,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTinyURLID sets the ID field of the mutation.
func withTinyURLID(id uint64) tinyurlOption {
	return func(m *TinyURLMutation) {
		var (
			err   error
			once  sync.Once
			value *TinyURL
		)
		m.oldValue = func(ctx context.Context) (*TinyURL, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TinyURL.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTinyURL sets the old TinyURL of the mutation.
func withTinyURL(node *TinyURL) tinyurlOption {
	return func(m *TinyURLMutation) {
		m.oldValue = func(context.Context) (*TinyURL, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TinyURLMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TinyURLMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of TinyURL entities.
func (m *TinyURLMutation) SetID(id uint64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TinyURLMutation) ID() (id uint64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TinyURLMutation) IDs(ctx context.Context) ([]uint64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uint64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TinyURL.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetURL sets the "url" field.
func (m *TinyURLMutation) SetURL(s string) {
	m.url = &s
}

// URL returns the value of the "url" field in the mutation.
func (m *TinyURLMutation) URL() (r string, exists bool) {
	v := m.url
	if v == nil {
		return
	}
	return *v, true
}

// OldURL returns the old "url" field's value of the TinyURL entity.
// If the TinyURL object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TinyURLMutation) OldURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldURL: %w", err)
	}
	return oldValue.URL, nil
}

// ResetURL resets all changes to the "url" field.
func (m *TinyURLMutation) ResetURL() {
	m.url = nil
}

// Where appends a list predicates to the TinyURLMutation builder.
func (m *TinyURLMutation) Where(ps ...predicate.TinyURL) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *TinyURLMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (TinyURL).
func (m *TinyURLMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TinyURLMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.url != nil {
		fields = append(fields, tinyurl.FieldURL)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TinyURLMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tinyurl.FieldURL:
		return m.URL()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TinyURLMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tinyurl.FieldURL:
		return m.OldURL(ctx)
	}
	return nil, fmt.Errorf("unknown TinyURL field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TinyURLMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tinyurl.FieldURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetURL(v)
		return nil
	}
	return fmt.Errorf("unknown TinyURL field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TinyURLMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TinyURLMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TinyURLMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TinyURL numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TinyURLMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TinyURLMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TinyURLMutation) ClearField(name string) error {
	return fmt.Errorf("unknown TinyURL nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TinyURLMutation) ResetField(name string) error {
	switch name {
	case tinyurl.FieldURL:
		m.ResetURL()
		return nil
	}
	return fmt.Errorf("unknown TinyURL field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TinyURLMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TinyURLMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TinyURLMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TinyURLMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TinyURLMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TinyURLMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TinyURLMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown TinyURL unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TinyURLMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown TinyURL edge %s", name)
}
