// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"shor_url/ent/predicate"
	"shor_url/ent/tinyurl"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TinyURLDelete is the builder for deleting a TinyURL entity.
type TinyURLDelete struct {
	config
	hooks    []Hook
	mutation *TinyURLMutation
}

// Where appends a list predicates to the TinyURLDelete builder.
func (tud *TinyURLDelete) Where(ps ...predicate.TinyURL) *TinyURLDelete {
	tud.mutation.Where(ps...)
	return tud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tud *TinyURLDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tud.hooks) == 0 {
		affected, err = tud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TinyURLMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tud.mutation = mutation
			affected, err = tud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tud.hooks) - 1; i >= 0; i-- {
			if tud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tud *TinyURLDelete) ExecX(ctx context.Context) int {
	n, err := tud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tud *TinyURLDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: tinyurl.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: tinyurl.FieldID,
			},
		},
	}
	if ps := tud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tud.driver, _spec)
}

// TinyURLDeleteOne is the builder for deleting a single TinyURL entity.
type TinyURLDeleteOne struct {
	tud *TinyURLDelete
}

// Exec executes the deletion query.
func (tudo *TinyURLDeleteOne) Exec(ctx context.Context) error {
	n, err := tudo.tud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tinyurl.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tudo *TinyURLDeleteOne) ExecX(ctx context.Context) {
	tudo.tud.ExecX(ctx)
}
