// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"shor_url/ent/predicate"
	"shor_url/ent/tinyurl"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TinyURLQuery is the builder for querying TinyURL entities.
type TinyURLQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TinyURL
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TinyURLQuery builder.
func (tuq *TinyURLQuery) Where(ps ...predicate.TinyURL) *TinyURLQuery {
	tuq.predicates = append(tuq.predicates, ps...)
	return tuq
}

// Limit adds a limit step to the query.
func (tuq *TinyURLQuery) Limit(limit int) *TinyURLQuery {
	tuq.limit = &limit
	return tuq
}

// Offset adds an offset step to the query.
func (tuq *TinyURLQuery) Offset(offset int) *TinyURLQuery {
	tuq.offset = &offset
	return tuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tuq *TinyURLQuery) Unique(unique bool) *TinyURLQuery {
	tuq.unique = &unique
	return tuq
}

// Order adds an order step to the query.
func (tuq *TinyURLQuery) Order(o ...OrderFunc) *TinyURLQuery {
	tuq.order = append(tuq.order, o...)
	return tuq
}

// First returns the first TinyURL entity from the query.
// Returns a *NotFoundError when no TinyURL was found.
func (tuq *TinyURLQuery) First(ctx context.Context) (*TinyURL, error) {
	nodes, err := tuq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tinyurl.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tuq *TinyURLQuery) FirstX(ctx context.Context) *TinyURL {
	node, err := tuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TinyURL ID from the query.
// Returns a *NotFoundError when no TinyURL ID was found.
func (tuq *TinyURLQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = tuq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tinyurl.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tuq *TinyURLQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := tuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TinyURL entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TinyURL entity is found.
// Returns a *NotFoundError when no TinyURL entities are found.
func (tuq *TinyURLQuery) Only(ctx context.Context) (*TinyURL, error) {
	nodes, err := tuq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tinyurl.Label}
	default:
		return nil, &NotSingularError{tinyurl.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tuq *TinyURLQuery) OnlyX(ctx context.Context) *TinyURL {
	node, err := tuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TinyURL ID in the query.
// Returns a *NotSingularError when more than one TinyURL ID is found.
// Returns a *NotFoundError when no entities are found.
func (tuq *TinyURLQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = tuq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tinyurl.Label}
	default:
		err = &NotSingularError{tinyurl.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tuq *TinyURLQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := tuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TinyURLs.
func (tuq *TinyURLQuery) All(ctx context.Context) ([]*TinyURL, error) {
	if err := tuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tuq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tuq *TinyURLQuery) AllX(ctx context.Context) []*TinyURL {
	nodes, err := tuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TinyURL IDs.
func (tuq *TinyURLQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := tuq.Select(tinyurl.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tuq *TinyURLQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := tuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tuq *TinyURLQuery) Count(ctx context.Context) (int, error) {
	if err := tuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tuq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tuq *TinyURLQuery) CountX(ctx context.Context) int {
	count, err := tuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tuq *TinyURLQuery) Exist(ctx context.Context) (bool, error) {
	if err := tuq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tuq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tuq *TinyURLQuery) ExistX(ctx context.Context) bool {
	exist, err := tuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TinyURLQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tuq *TinyURLQuery) Clone() *TinyURLQuery {
	if tuq == nil {
		return nil
	}
	return &TinyURLQuery{
		config:     tuq.config,
		limit:      tuq.limit,
		offset:     tuq.offset,
		order:      append([]OrderFunc{}, tuq.order...),
		predicates: append([]predicate.TinyURL{}, tuq.predicates...),
		// clone intermediate query.
		sql:    tuq.sql.Clone(),
		path:   tuq.path,
		unique: tuq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		URL string `json:"url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TinyURL.Query().
//		GroupBy(tinyurl.FieldURL).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tuq *TinyURLQuery) GroupBy(field string, fields ...string) *TinyURLGroupBy {
	group := &TinyURLGroupBy{config: tuq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tuq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		URL string `json:"url,omitempty"`
//	}
//
//	client.TinyURL.Query().
//		Select(tinyurl.FieldURL).
//		Scan(ctx, &v)
//
func (tuq *TinyURLQuery) Select(fields ...string) *TinyURLSelect {
	tuq.fields = append(tuq.fields, fields...)
	return &TinyURLSelect{TinyURLQuery: tuq}
}

func (tuq *TinyURLQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tuq.fields {
		if !tinyurl.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tuq.path != nil {
		prev, err := tuq.path(ctx)
		if err != nil {
			return err
		}
		tuq.sql = prev
	}
	return nil
}

func (tuq *TinyURLQuery) sqlAll(ctx context.Context) ([]*TinyURL, error) {
	var (
		nodes = []*TinyURL{}
		_spec = tuq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TinyURL{config: tuq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, tuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tuq *TinyURLQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tuq.querySpec()
	_spec.Node.Columns = tuq.fields
	if len(tuq.fields) > 0 {
		_spec.Unique = tuq.unique != nil && *tuq.unique
	}
	return sqlgraph.CountNodes(ctx, tuq.driver, _spec)
}

func (tuq *TinyURLQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tuq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tuq *TinyURLQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tinyurl.Table,
			Columns: tinyurl.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: tinyurl.FieldID,
			},
		},
		From:   tuq.sql,
		Unique: true,
	}
	if unique := tuq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tuq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tinyurl.FieldID)
		for i := range fields {
			if fields[i] != tinyurl.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tuq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tuq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tuq *TinyURLQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tuq.driver.Dialect())
	t1 := builder.Table(tinyurl.Table)
	columns := tuq.fields
	if len(columns) == 0 {
		columns = tinyurl.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tuq.sql != nil {
		selector = tuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tuq.unique != nil && *tuq.unique {
		selector.Distinct()
	}
	for _, p := range tuq.predicates {
		p(selector)
	}
	for _, p := range tuq.order {
		p(selector)
	}
	if offset := tuq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tuq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TinyURLGroupBy is the group-by builder for TinyURL entities.
type TinyURLGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tugb *TinyURLGroupBy) Aggregate(fns ...AggregateFunc) *TinyURLGroupBy {
	tugb.fns = append(tugb.fns, fns...)
	return tugb
}

// Scan applies the group-by query and scans the result into the given value.
func (tugb *TinyURLGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tugb.path(ctx)
	if err != nil {
		return err
	}
	tugb.sql = query
	return tugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tugb *TinyURLGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tugb *TinyURLGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tugb.fields) > 1 {
		return nil, errors.New("ent: TinyURLGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tugb *TinyURLGroupBy) StringsX(ctx context.Context) []string {
	v, err := tugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tugb *TinyURLGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tinyurl.Label}
	default:
		err = fmt.Errorf("ent: TinyURLGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tugb *TinyURLGroupBy) StringX(ctx context.Context) string {
	v, err := tugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tugb *TinyURLGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tugb.fields) > 1 {
		return nil, errors.New("ent: TinyURLGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tugb *TinyURLGroupBy) IntsX(ctx context.Context) []int {
	v, err := tugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tugb *TinyURLGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tinyurl.Label}
	default:
		err = fmt.Errorf("ent: TinyURLGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tugb *TinyURLGroupBy) IntX(ctx context.Context) int {
	v, err := tugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tugb *TinyURLGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tugb.fields) > 1 {
		return nil, errors.New("ent: TinyURLGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tugb *TinyURLGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tugb *TinyURLGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tinyurl.Label}
	default:
		err = fmt.Errorf("ent: TinyURLGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tugb *TinyURLGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tugb *TinyURLGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tugb.fields) > 1 {
		return nil, errors.New("ent: TinyURLGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tugb *TinyURLGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tugb *TinyURLGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tinyurl.Label}
	default:
		err = fmt.Errorf("ent: TinyURLGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tugb *TinyURLGroupBy) BoolX(ctx context.Context) bool {
	v, err := tugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tugb *TinyURLGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tugb.fields {
		if !tinyurl.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tugb *TinyURLGroupBy) sqlQuery() *sql.Selector {
	selector := tugb.sql.Select()
	aggregation := make([]string, 0, len(tugb.fns))
	for _, fn := range tugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tugb.fields)+len(tugb.fns))
		for _, f := range tugb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tugb.fields...)...)
}

// TinyURLSelect is the builder for selecting fields of TinyURL entities.
type TinyURLSelect struct {
	*TinyURLQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tus *TinyURLSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tus.prepareQuery(ctx); err != nil {
		return err
	}
	tus.sql = tus.TinyURLQuery.sqlQuery(ctx)
	return tus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tus *TinyURLSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tus *TinyURLSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tus.fields) > 1 {
		return nil, errors.New("ent: TinyURLSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tus *TinyURLSelect) StringsX(ctx context.Context) []string {
	v, err := tus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tus *TinyURLSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tinyurl.Label}
	default:
		err = fmt.Errorf("ent: TinyURLSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tus *TinyURLSelect) StringX(ctx context.Context) string {
	v, err := tus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tus *TinyURLSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tus.fields) > 1 {
		return nil, errors.New("ent: TinyURLSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tus *TinyURLSelect) IntsX(ctx context.Context) []int {
	v, err := tus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tus *TinyURLSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tinyurl.Label}
	default:
		err = fmt.Errorf("ent: TinyURLSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tus *TinyURLSelect) IntX(ctx context.Context) int {
	v, err := tus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tus *TinyURLSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tus.fields) > 1 {
		return nil, errors.New("ent: TinyURLSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tus *TinyURLSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tus *TinyURLSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tinyurl.Label}
	default:
		err = fmt.Errorf("ent: TinyURLSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tus *TinyURLSelect) Float64X(ctx context.Context) float64 {
	v, err := tus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tus *TinyURLSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tus.fields) > 1 {
		return nil, errors.New("ent: TinyURLSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tus *TinyURLSelect) BoolsX(ctx context.Context) []bool {
	v, err := tus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tus *TinyURLSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tinyurl.Label}
	default:
		err = fmt.Errorf("ent: TinyURLSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tus *TinyURLSelect) BoolX(ctx context.Context) bool {
	v, err := tus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tus *TinyURLSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tus.sql.Query()
	if err := tus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
